export APP_PORT="9000"
export DB_HOST="localhost"
export DB_PORT="5432"
export DB_USERNAME="postgres"
export DB_PASSWORD=""
export DB_NAME="asset_management"
export EVENT_SERVICE_URL="http://34.70.86.33:9035"
export EVENT_API_TIMEOUT="3"
export JWT_SECRET="secret" # change it
export TOKEN_EXPIRY="5" # in minutes

