export APP_PORT="9000"
export DB_HOST="localhost"
export DB_PORT="5432"
export DB_USERNAME="postgres"
export DB_PASSWORD="12345"
export DB_NAME="asset_management"
export EVENT_SERVICE_URL="http://localhost:9035"
export EVENT_API_TIMEOUT="3"
export JWT_SECRET="secret" # change it
export TOKEN_EXPIRY="5" # in minutes


docker run -e APP_PORT=9000 -e DB_PORT=5432 -e EVENT_SERVICE_URL=http://localhost:9035 -e DB_HOST=localhost -e DB_USERNAME=postgres -e DB_PASSWORD=12345 -e DB_NAME=asset_management -e EVENT_API_TIMEOUT=3 -e JWT_SECRET=secret -e TOKEN_EXPIRY=5 -d --network=host -p 9000:9000 asset-mgmt-sys
docker build . -t asset-mgmt-sys

docker logs container_id
docker ps -a
docker stop name 